const CONFIG = {"appId":"lennys-podcast-tara-seshan-ai-third-era","appVersion":"efdbddba7694","version":"95b5ba6e3e27ff36","media":{"size":78468771,"sha256":"d8c4e04281f7d60fffb8675a38b28e02b4889fb297cb3de626b598109c4a69bc","chunkSize":8388608,"parts":[{"path":"audio/part-000.bin","size":8388608,"sha256":"2a34c326685ce56610e6e4104edf2dcca8aa41604d03df54c6a330e1dd85b1cd"},{"path":"audio/part-001.bin","size":8388608,"sha256":"59ddf1884ce7efc4861175afca35669742a4e0dfbb2f0470522d852fc68f8e7a"},{"path":"audio/part-002.bin","size":8388608,"sha256":"9f3ca10262e96e7ae5cc994ea66228922e8164c8d8d5755b80b5adc494c4dd48"},{"path":"audio/part-003.bin","size":8388608,"sha256":"17a5f1c94e82e436ed6436b5af9eccaf89c636cfdd4b242aaf01687191ddde0d"},{"path":"audio/part-004.bin","size":8388608,"sha256":"afdf6d829beefb9d189d43063a53f87f381391c05476bfdfcbf2a3a9c3153a1d"},{"path":"audio/part-005.bin","size":8388608,"sha256":"9e42dc073ce1de80df2e9876e4b7f7a32616c64d46ae7f1911f30d54ad7d7e2b"},{"path":"audio/part-006.bin","size":8388608,"sha256":"6f67367c7c159a721ecdadcd63a277f5c5324b9e880c79f20416ddd68c3f627b"},{"path":"audio/part-007.bin","size":8388608,"sha256":"5ae3fb2da8252e26052240e83b2115c7bc2a367d88a160f4f3441cb8d0ce1761"},{"path":"audio/part-008.bin","size":8388608,"sha256":"caf3cc9eacdc1154fbae802dba383703fec712a5294f275b804e811add13eaed"},{"path":"audio/part-009.bin","size":2971299,"sha256":"17626a15e0af3cf8f5f32ca5e38e53efb1173d92695890b68ad7b07a914e856a"}]},"shell":[{"path":"index.html","sha256":"6d212076c7a099be07d49375a5121eaf015f6e0b30efd5fb4bfe1f1b1702579d","source":"reader-shell-6d212076c7a099be.bin"},{"path":"pwa.js","sha256":"5f50c977f80098f3914986c5749f01e72c8e338e37000d4ff7979989cecf407c"},{"path":"media-config.js","sha256":"1cba061db4d7b254efa0c39dcd2e76b124e5117386a70cd077f0de50b32b8cc7"},{"path":"manifest.webmanifest","sha256":"d5ac70f0dd6185dfc61f2c29de011952ec0ccdc8c238dedfbfe0e5c673283ff3"},{"path":"icon-180.png","sha256":"153b31cc18f328274916430ac132b076c1ced5a24890463d4653428b4c1c944a"},{"path":"icon-192.png","sha256":"200b1d32c05d8aae2bc8cfacc941b40290cb69315f5d52ae2be0bd4b6c7c4d42"},{"path":"icon-512.png","sha256":"42ef2d3a17922720872b585a8f3ecb515f89e92304f4a7a60046d761e9551e17"}]};
/* CONFIG is generated by build.py; all cached assets are verified before use. */
const prefix = 'reader-' + CONFIG.appId + '-' + encodeURIComponent(new URL(self.registration.scope).pathname) + '-';
const SHELL = prefix + 'shell-' + CONFIG.version;
const MEDIA = prefix + 'audio-' + CONFIG.media.sha256;
const absolute = path => new URL(path, self.registration.scope).href;
const digest = async data => Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256', data)), x => x.toString(16).padStart(2, '0')).join('');
self.addEventListener('install', event => event.waitUntil((async () => {
  const cache = await caches.open(SHELL);
  try {
  for (const asset of CONFIG.shell) {
    // HTML responses may be transformed by a host. The content-addressed binary
    // payload keeps verification exact; never cache an unverified login/error page.
    const response = await fetch(absolute(asset.source || (asset.path === 'index.html' ? '' : asset.path)), { cache: 'no-store', redirect: 'error' });
    if (!response.ok) throw new Error('页面下载失败：' + asset.path + ' (' + response.status + ')');
    const bytes = await response.arrayBuffer();
    if (await digest(bytes) !== asset.sha256) throw new Error('页面下载校验失败：' + asset.path);
    const headers = new Headers(response.headers);
    headers.delete('Content-Encoding');
    headers.set('Content-Length', String(bytes.byteLength));
    if (asset.path === 'index.html') {
      headers.set('Content-Type', 'text/html; charset=utf-8');
      headers.delete('Content-Disposition');
    }
    await cache.put(absolute(asset.path), new Response(bytes, { headers }));
  }
  await self.skipWaiting();
  } catch (error) { await caches.delete(SHELL); throw error; }
})()));
self.addEventListener('message', event => {
  if (event.data && event.data.type === 'GET_VERSION' && event.ports[0]) event.ports[0].postMessage({ version: CONFIG.appVersion || CONFIG.version, audio: CONFIG.media.sha256 });
});
self.addEventListener('activate', event => event.waitUntil((async () => {
  await self.clients.claim();
  for (const name of await caches.keys()) if (name.startsWith(prefix + 'shell-') && name !== SHELL) await caches.delete(name);
})()));
async function chunkBytes(part) {
  const cache = await caches.open(MEDIA);
  let response = await cache.match(absolute(part.path));
  if (!response || response.headers.get('X-Verified-SHA256') !== part.sha256) {
    response = await fetch(absolute(part.path), { cache: 'no-store', redirect: 'error' });
    if (!response.ok) throw new Error('音频未下载');
    const data = await response.arrayBuffer();
    if (data.byteLength !== part.size || await digest(data) !== part.sha256) throw new Error('音频文件不完整');
    return new Uint8Array(data);
  }
  const data = new Uint8Array(await response.arrayBuffer());
  if (data.byteLength !== part.size) throw new Error('音频缓存不完整');
  return data;
}
async function serveAudio(request) {
  const total = CONFIG.media.size, range = request.headers.get('range');
  let start = 0, end = total - 1;
  if (range) {
    const m = /^bytes=(\d*)-(\d*)$/.exec(range);
    if (!m || (!m[1] && !m[2])) return new Response(null, { status: 416, headers: { 'Content-Range': 'bytes */' + total } });
    if (!m[1]) start = Math.max(0, total - Number(m[2]));
    else { start = Number(m[1]); if (m[2]) end = Math.min(end, Number(m[2])); }
    if (!Number.isSafeInteger(start) || !Number.isSafeInteger(end) || start > end || start >= total) return new Response(null, { status: 416, headers: { 'Content-Range': 'bytes */' + total } });
  }
  const headers = { 'Content-Type': 'audio/mpeg', 'Accept-Ranges': 'bytes', 'Content-Length': String(end - start + 1), 'Cache-Control': 'no-store' };
  if (range) headers['Content-Range'] = `bytes ${start}-${end}/${total}`;
  if (request.method === 'HEAD') return new Response(null, { status: range ? 206 : 200, headers });
  let index = Math.floor(start / CONFIG.media.chunkSize), cancelled = false;
  // Bound memory to one 8 MiB part even for a whole-file request.
  const stream = new ReadableStream({
    async pull(controller) {
      try {
        const part = CONFIG.media.parts[index];
        const bytes = await chunkBytes(part);
        if (cancelled) return;
        const offset = index * CONFIG.media.chunkSize;
        controller.enqueue(bytes.subarray(Math.max(0, start - offset), Math.min(bytes.length, end - offset + 1)));
        index++;
        if (index * CONFIG.media.chunkSize > end) controller.close();
      } catch (error) { if (!cancelled) controller.error(error); }
    },
    cancel() { cancelled = true; }
  });
  return new Response(stream, { status: range ? 206 : 200, headers });
}
self.addEventListener('fetch', event => {
  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin || !['GET', 'HEAD'].includes(event.request.method)) return;
  if (url.href.split('?')[0] === absolute('media.mp3')) { event.respondWith(serveAudio(event.request)); return; }
  if (event.request.method !== 'GET') return;
  if (event.request.mode === 'navigate' && [absolute(''), absolute('index.html')].includes(url.href.split('?')[0])) {
    event.respondWith(caches.open(SHELL).then(cache => cache.match(absolute('index.html'))).then(r => r || fetch(event.request))); return;
  }
  const path = CONFIG.shell.find(asset => absolute(asset.path) === url.href);
  if (path) event.respondWith(caches.open(SHELL).then(cache => cache.match(url.href)).then(r => r || fetch(event.request)));
});
